# Generated by Django 3.2 on 2021-04-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('project_id', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('leader_id', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'activities',
            },
        ),
    ]
