# Generated by Django 3.2 on 2021-04-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20210415_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='country_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='state_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
