# Generated by Django 3.2 on 2021-04-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20210416_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('responsible_id', models.IntegerField()),
                ('website', models.URLField()),
            ],
        ),
    ]
