# Generated by Django 3.2 on 2021-04-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='responsible_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
