# Generated by Django 3.2 on 2021-04-16 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_auto_20210416_2038'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivityComment',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='ActivityNeed',
            new_name='Need',
        ),
        migrations.RenameModel(
            old_name='ActivityRating',
            new_name='Rating',
        ),
    ]
